Feature/#6 join
kosSpringBoot2/geulkkoli pull request #18
Opened 2023-04-04 06:44 UTC by godchaean

findByPhoneNo 기능 생성 및 erd에 따른 변수명 변경 처리 했습니다.

2023-04-04 08:48 UTC, takoeats approved these changes
확인

2023-04-04 15:51 UTC, Hoogokok approved these changes

2023-04-05 00:07 UTC, takoeats approved these changes
확인

2023-04-05 02:14 UTC, torahoo requested changes
너무너무 잘봤습니다.

2023-04-05 02:14 UTC, torahoo approved these changes

2023-04-05 02:17 UTC, seungin2 reviewed
complate

2023-04-05 02:23 UTC, devyoon96 reviewed
check!

2023-04-05 02:26 UTC, seungin2 approved these changes

2023-04-05 02:49 UTC, merged

2023-04-05 02:51 UTC, godchaean reviewed
확인

2023-04-05 02:51 UTC, godchaean commented on geulkkoli/src/main/resources/errors.properties
File Encodings 설정 UTF-8로 바꿔주세요. 글자가 다 깨져서 안 보입니다.