Feature/#36 post page author
kosSpringBoot2/geulkkoli pull request #37
Opened 2023-04-12 05:12 UTC by torahoo

게시글에 글쓴이 정보가 보이게 끔 수정하였습니다.

2023-04-12 05:14 UTC, seungin2 approved these changes
ok

2023-04-12 12:12 UTC, Hoogokok requested changes

2023-04-12 12:12 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/post/ImplPostRepositoryTest.java
interface PostRepository에 대한 테스트라고 볼 수 있으니 ImplPostRepositoryTest를 일반적인 PostRepositoryTest로 바꾸는 건 어떨 까요

2023-04-12 12:12 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/post/PostServiceTest.java
>          log.info("@Test ::1 one={}", postService.findById(1L));
log를 선언한 이유가 뭔가요?

2023-04-12 12:12 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/post/PostServiceTest.java
> + * TestDataInit Class 참조
TestDataInit 클래스의 목적은 화면의 보여줄 정보가 없어서 사용하는 용도였습니다. 결국 이 데이터는 DB에 데이터가 있어서 더 이상 불필요해 진다면 사라질  테스트 더미 데이터라고 볼 수 있습니다. 

이때 이 아래의 테스트들은 통과되지 않을 겁니다. 왜냐하면 이 테스트들에 필요한 값을 외부 클래스인 TestDataIntit에 의존하고 있기 때문 입니다. 

충분히 작성된 테스트는 보통 테스트 대상의 구현이 바뀌어도 테스트 코드 바뀌지 않는다고 합니다. 

하지만 아래의 테스트 코드들은 테스트 대상이 바뀐 것도 아닌데 실패가 예견되는 테스트 코드 입니다. 즉 충분히 작성된 게 아닌 테스트 코드인 셈 입니다.

https://mangkyu.tistory.com/144 이 블로그의 given. when then 패턴의 given의 주의해서 주입할 데이터를 골라보는 게 어떨까요?

2023-04-13 00:03 UTC, takoeats approved these changes
잘 했을거에요

2023-04-13 01:33 UTC, godchaean reviewed
확인

2023-04-13 01:34 UTC, godchaean approved these changes

2023-04-14 02:01 UTC, Hoogokok approved these changes

2023-04-14 02:02 UTC, merged