Feat/#45 find user id and pw
kosSpringBoot2/geulkkoli pull request #53
Opened 2023-04-28 09:51 UTC by godchaean

로그인 화면에서 이메일 찾기 & 비밀번호 찾기(이메일로 임시 비밀번호 전송) 구현

2023-04-30 02:13 UTC, Hoogokok requested changes
몇 가지 의문점을 적어 봣습니다.  중복된 메서드명이 많이 보이는 데 이에 관해선
[](url)****

2023-04-30 02:13 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/UserRepository.java
> +    Optional<User> findByEmail(@Param("email") String email, @Param("userName") String userName, @Param("phoneNo") String phoneNo);
회원 이름, 이메일, 핸드폰 번호 모두로 찾고 있는데 findByEmail이라는 이름이 적절할까요?

2023-04-30 02:13 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/UserRepository.java
> +    Optional<User> findByEmail(@Param("userName") String userName, @Param("phoneNo") String phoneNo);
회원 이름 핸드폰 번호 모두로 찾고 있는데 findByEmail이라는 이름이 적절할까요? 이 메서드는 위 메서드와 다른 일을 하고 있는데 이름이 같아서 쓸 때 헷갈릴 것 같아요

2023-04-30 02:13 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/application/security/UserSecurityService.java
> +    public String tempPassword() {
이 코드는 현재 어떻게 테스트 할 수 있나요? 안에서 랜덤한 값을 생성해서 반환하기 때문에 값을 예상해서 테스트하기 힘들 거 같은데요??

2023-04-30 02:13 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
> +
위의 세 메서드는 다 다른 매개변수를 받으면서, 각각 이메일로 찾기, 이름, 핸드폰 번호로 찾기, 이메일,핸드폰,이름으로 찾기로 다른 행위를 하고 있는 데 같은 메서드명을 쓰는 건 혼란스러운 거 같아요. 더 명확한 이름을 지정해야 하지 않을까요?

2023-05-02 00:17 UTC, devyoon96 approved these changes
check

2023-05-02 00:25 UTC, torahoo approved these changes
확인했습니다. 고생하셨습니다~

2023-05-02 00:32 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/UserRepository.java
> +    Optional<User> findByEmail(@Param("email") String email, @Param("userName") String userName, @Param("phoneNo") String phoneNo);
Find By가 ~를 찾는 것으로 이해했습니다. findByUserNameAndPhoneNo와 findByUserInfo로 변경했습니다.

2023-05-02 00:33 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/UserRepository.java
> +    Optional<User> findByEmail(@Param("userName") String userName, @Param("phoneNo") String phoneNo);
이에 대한 내용은 위 코멘트와 동일합니다.

2023-05-02 00:37 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
> +
이것 역시 변경했습니다.

2023-05-02 00:42 UTC, seungin2 approved these changes
Good

2023-05-02 02:03 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/application/security/UserSecurityService.java
> +    public String tempPassword() {
하나의 메소드를 클래스로 분리시키고 PasswordService도 만들어 정리하였습니다.

2023-05-02 02:08 UTC, Hoogokok approved these changes

2023-05-02 02:08 UTC, merged

2023-05-02 03:41 UTC, seungin2 reviewed
ok