Feature/#61 comment
kosSpringBoot2/geulkkoli pull request #66
Opened 2023-05-26 12:42 UTC by seungin2

commnet merge 문제로 다시 올립니다.

2023-05-26 14:53 UTC, godchaean approved these changes
멋집니다

2023-06-03 16:54 UTC, takoeats approved these changes
믿고 있었다구

2023-06-03 18:42 UTC, godchaean approved these changes

2023-06-03 23:22 UTC, Hoogokok requested changes

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/web/comment/CommentController.java
> +        return getCommentsList(post.getComments());
Comments는 엔티티 인데 이를 dto로 쓰고 있어요. 댓글 본문만 받아오면 되는데 이는 dto를 써야할 일 같습니다. 엔티티는 db에 접근해서 쓰는 만큼 표현 계층에서 직접적으로 접근하는 건 지양해야 합니다.
https://wildeveloperetrain.tistory.com/101
의 글을 참고해 봐도 좋겠습니다.

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/web/comment/CommentController.java
> +        return getCommentsList(post.getComments());
public class CommentDto {

    private String commentBody;

    private String nickName;

    private LocalDateTime date;

    public CommentDto() {
    }

    @Builder
    public CommentDto(String commentBody, String nickName, LocalDateTime date) {
        this.commentBody = commentBody;
        this.nickName = nickName;
        this.date = date;
    }

    public void setCommentBody(String commentBody) {
        this.commentBody = commentBody;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public String getCommentBody() {
        return commentBody;
    }

    public String getNickName() {
        return nickName;
    }

    public LocalDateTime getDate() {
        return date;
    }
}

이런 방식의 dto 의 예시도 있을 거 같네요

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/domain/comment/CommentsService.java
> +        commentsRepository.save(user.writeComment(commentBody, post));
user 도메인에서 이미 Comments를 생성하고 있는 걸로 아는 데 파라미터 그대로 Comments를 받기보다 dto를 받아서 Comments를 만들 때 필요한 값만 주입하는 방식은 어떨까요?

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/web/comment/CommentController.java
> +    @PutMapping("/{postId}")
👍 GET,POST,PUT,DELETE를 모두 적절하게 썼네요.😃

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/main/resources/static/js/comment.js
> +        if (newComment.nickName == validName) {
(newComment.nickName === validName)를 해야 이 로직이 동작합니다

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/comment/CommentServiceTest.java
> +public class CommentServiceTest {
테스트 클래스에는 public 선언을 해주지 않아도 됩니다

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/comment/CommentServiceTest.java
> +                    .build();
복수의 commentBodyDTO를 넣어려고 for문을 쓰신 것 같아요.  이런 복수의 입력값을 원하셨다면     @ParameterizedTest와  @MethodSource 를 쓰는 방식이 있습니다. 
https://www.baeldung.com/parameterized-tests-junit-5 4.6 목록을 보면 좋습니다. 

``

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/comment/CommentServiceTest.java
> +    @Test
`` private static Stream<CommentBodyDTO> commentBodyDTOStream() {
        return Stream.of(
                CommentBodyDTO.builder()
                        .commentBody("test")
                        .build(),
                CommentBodyDTO.builder()
                        .commentBody("test")
                        .build(),
                CommentBodyDTO.builder()
                        .commentBody("test")
                        .build()
        );
    }``를 만들고

` @ParameterizedTest
    @MethodSource("commentBodyDTOStream")`를 선언하고 
   ` void commentDelete(CommentBodyDTO input)`로 메서드 시그니처를 바꾸고
`        commentsService.writeComment(input, post01, user);
`를 하면 같은 테스트 결과를 얻을 수 있습니다. 이러면 테스트 코드에서 1. body값을 서로 다른 값을 주면서 복수의 파리미터 값을 주입하면서 테스트할 수 있습니다.

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/comment/CommentsRepositoryTest.java
> +        for (int i = 0; i < 10; ++i) {
위의 남긴 리뷰를 참고해주세요

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/favorites/FavoriteServiceTest.java
> +        //then
`favoriteService.favoriteCheck()`은 optional을 반환해서 예외를 반환하지 않습니다.  따라서 동작하는 않는 코드 입니다.

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/domain/favorites/FavoriteServiceTest.java
> +        assertThat(favorites1.getUser()).isEqualTo(user);
복수의 assertThat를 쓴다면 assertAll을 써보세요.
`     assertAll(
                () -> assertThat(optionalFavorites).isPresent(),
                () -> assertThat(optionalFavorites).get().hasFieldOrPropertyWithValue("post",post01),
                () -> assertThat(optionalFavorites).get().hasFieldOrPropertyWithValue("user",user)
        );`

또한 유저가 게시글의 좋아요를 눌렀다면 좋아요 클래스 안에 유저,게시글 정보등이 담겨져 있을테니 테스트를 한다면 이들 모두를 테스트하는 게 더 바람직해 보입니다.

2023-06-03 23:22 UTC, Hoogokok commented on geulkkoli/src/test/java/com/geulkkoli/web/CommentControllerTest.java
> +@Slf4j
@Slf4j는 테스트 코드에 왜 있나요??

2023-06-04 11:46 UTC, Hoogokok approved these changes

2023-06-04 11:48 UTC, merged