Feature/#60 coloring calander by amount of activity
kosSpringBoot2/geulkkoli pull request #73
Opened 2023-06-12 09:56 UTC by godchaean

유저가 포스팅한 날들에 대한 달력 표시 정도 구현했습니다.

2023-06-12 11:03 UTC, takoeats approved these changes
아주 멋지네요

2023-06-12 11:20 UTC, torahoo approved these changes
고생하셨습니다~

2023-06-12 11:20 UTC, torahoo commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/PostRepository.java
> +    List<Post> findByUser(User user);
user.getPosts로 repository에 새로 메서드 만들 필요 없이 쓸수 있습니다.
User엔티티에 post가 set<Post> posts  로 선언되있는게 있어서 그거 보시면 될거같습니다.

2023-06-12 11:20 UTC, torahoo commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/service/PostService.java
> +        List<Post> posts = postRepository.findByUser(user);
이부분이 아까 말한걸 쓸수 있는 부분인데 여기서 List<Post> posts = new ArrayList<>(user.getPosts); 로 바꿀수 있을 겁니다. user.getPosts가 set으로 반환이 되기에 arrayList로 바꿔주는 작업이 필요합니다.

2023-06-12 11:26 UTC, seungin2 approved these changes
ok

2023-06-12 11:26 UTC, seungin2 commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/ConfigDate.java
> +    public LocalDateTime setCreatedAtForCalendarTest(LocalDateTime localDateTime) {
테스트를 위한 메소드인지 헷갈리네요. 명확한 메소드명이나 주석이 필요해보이네요.

2023-06-12 11:26 UTC, seungin2 commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
> +    public void edit(Long id, UserInfoEditFormDto userInfoEditFormDto) {
수정하는 메소드로 보이는데 readOnly이네요 확인요망

2023-06-12 11:38 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/ConfigDate.java
> +    public LocalDateTime setCreatedAtForCalendarTest(LocalDateTime localDateTime) {
(추후 제거)라는 주석 달아 수정했습니다

2023-06-12 11:38 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/service/UserService.java
> +    public void edit(Long id, UserInfoEditFormDto userInfoEditFormDto) {
잘못 기입했습니다. 제거했습니다.

2023-06-12 12:11 UTC, Hoogokok requested changes

2023-06-12 12:11 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/service/PostService.java
> +
생성날짜만 가져오는 거면 생생날짜만 조회해서 가져오면 될거 같습니다. 현재는  일치하는 조건의 모든 게시글  정보를 db에서 가져와서 생성날짜를 꺼내서 가져오는 데 필요하지 않는 데이터도 같이 가져오니 수정이 필요해 보입니다.

2023-06-12 12:11 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/User.java
> +    public Post writePost(AddDTO addDTO, LocalDateTime localDateTime) {
이거 역시 테스트용도로 만든 거 같은데 테스트 용도이고 실제 서비스에서 사용되지 않아야 하며 반드시 수정 되야 한다고 명시해야 할 것 같아요

2023-06-12 12:11 UTC, Hoogokok commented on geulkkoli/src/main/java/com/geulkkoli/web/myPage/dto/MyPageFormDto.java
> +    public void myPageFormDto(String userName, String email) {
생성자 주입 방식은  public MypageFormDto(String userName, String email) 로 시작되야 합니다. 현재는 메서드 주입 방식입니다.

2023-06-12 12:11 UTC, Hoogokok commented on geulkkoli/src/main/resources/templates/post/postPage.html
> +
이건 하트 모양 저작권 때문에 넣은 거라서 다시 추가해주세요

2023-06-13 06:43 UTC, godchaean commented on geulkkoli/src/main/resources/templates/post/postPage.html
> +
다시 복구했습니다.

2023-06-13 06:47 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/user/User.java
> +    public Post writePost(AddDTO addDTO, LocalDateTime localDateTime) {
(추후 제거) 표시 추가했습니다.

2023-06-13 06:49 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/web/myPage/dto/MyPageFormDto.java
> +    public void myPageFormDto(String userName, String email) {
떠나간 윤 모 씨가 한 작업이지만 제가 수정했습니다.

2023-06-13 08:06 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/service/PostService.java
> +
postRepository에서 날짜만 가져오도록 쿼리 추가하여 수정했습니다. 다시 올리면 코드로 확인 부탁합니다.

2023-06-13 08:07 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/PostRepository.java
> +    List<Post> findByUser(User user);
user의 Post를 다 가져오게 된다는 지적으로 날짜만 가져오게 하는 쿼리로 수정했습니다. 반영한 코드로 다시 올리겠습니다.

2023-06-13 08:08 UTC, godchaean commented on geulkkoli/src/main/java/com/geulkkoli/domain/post/service/PostService.java
> +        List<Post> posts = postRepository.findByUser(user);
위 코멘트 참고 바랍니다!

2023-06-13 08:24 UTC, closed without merging